on: [push]

name: build

jobs:
  check:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
          profile: minimal
      - uses: Swatinem/rust-cache@v2 
      - name: Generate Prisma client
        uses: actions-rs/cargo@v1
        with:
          command: prisma
          args: generate
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
