name: release

on: 
  push:
    tags:
      - 'v*'

jobs:
  create-release:
   runs-on: ubuntu-latest
   steps:
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        release_name: ${{ github.event.inputs.release_tag }}
  build-win64:
    runs-on: windows-latest
    needs: [create-release]
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt
        profile: minimal
    - uses: Swatinem/rust-cache@v2 
    - name: Generate Prisma client
      uses: actions-rs/cargo@v1
      with:
        command: prisma
        args: generate
    - name: Build in release mode
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/tcd.exe
        asset_name: tcd-win64.exe
        tag: ${{ github.event.inputs.release_tag }}
        overwrite: true
  build-linux64:
    runs-on: ubuntu-latest
    needs: [create-release]
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt
        profile: minimal
    - uses: Swatinem/rust-cache@v2 
    - name: Generate Prisma client
      uses: actions-rs/cargo@v1
      with:
        command: prisma
        args: generate
    - name: Build in release mode
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/tcd
        asset_name: tcd-linux64
        tag: ${{ github.event.inputs.release_tag }}
        overwrite: true
