on: [push]

name: build

jobs:
  check:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Generate Prisma client
        uses: actions-rs/cargo@v1
        with:
          command: prisma generate
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
